# Configuration file for BOA

task: "fft"
version: "0.1"

# Specification of statistical model
model:
  name: "gp"

  # Parameters passed to model's constructor
  parameters:
    kernel: "rbf"
    num_optimizer_restarts: 3

# Specification of acquisition function
acquisition:
  name: "sms-ego"

  # Parameters passed to acquisition function's constructor
  parameters:
    gain: 1
    epsilon: 1
    # ...

# Specification of optimizer
optimizer:
  name: "default"
  parameters:
    max_num_iterations: 25
    batch_size: 5

# Specification of objective function
objective:
  # Name of module containing a class `Objective` (which must inherit from AbstractObjective)
  name: "function.py"

  # Parameters passed to the constructor of `Objective`
  parameters: {}

# Data can be written / loaded from a file named after task (e.g., fft.json)
data:
  # Set `load` to read data from file or `random` to select random candidate points
  init: "random" # or "load"

  # The following options are only applicable if `init` is set to `random`.
  seed: 42
  size: 3
